### ISSUE TITLE
DistributedDataParallel running chunkipy

### ISSUE THREAD

**Issue by siebeniris** [gioelecrispo/chunkipy#1]
Hi, 

thanks so much for the amazing tool! It is very useful.

Since it is built on transformers, would we be able to run the chunkipy on accelerate with multiple GPUs?

thanks!

**Comment by gioelecrispo** [comment]
Hello siebeniris, thanks for using it.
Basically, two phases exists: recursive splitting and chunks building. While the latter does not use neural networks to aggregate the text parts into chunks, the former relies on `langdetect` and `stanza`.
`langdetect` is used to detect the language and it uses statistical approach to perform it; thus, GPUs won't be useful in this case; on the other hand, `stanza` uses neural network to perform the tokenization and sentence segmentation (pytorch based, not transformer based - correct me if I am wrong). 
By default, gpu is enabled (see this link from [stanza documentation](https://stanfordnlp.github.io/stanza/pipeline.html)) but multiple GPUs feature it is not available yet (see the comment by the mantain in this [Github issue](https://github.com/stanfordnlp/stanza/discussions/1036)). 

In any case, I would not overcomplicate the structure of the code by introducing multiple GPUs  processing; the model running sentence segmentation is quite a small one and it is relatively fast even on long documents. You could write a code that parallelize on data instead if you need to process more documents. Alternatively, you can always change the splitting method with different libraries or your custom logic as `chunkipy` allows it.

**Comment by siebeniris** [comment]
Great! Thanks a lot!
